export const PAGE_ROUTE = {
  LANDING_PAGE: 'LANDING_PAGE',
  MATCHES: 'MATCHES',
  PLAYER_SETUP_PAGE: 'PLAYER_SETUP_PAGE',
  PLAYER_LIST: 'PLAYER_LIST',
  GAME_TYPE_SELECTION_PAGE: 'GAME_TYPE_SELECTION_PAGE',
};
